GET http://localhost:8080/

### get all events
GET http://localhost:8080/events

### get events details
GET http://localhost:8080/events/100

### get insert events
POST http://localhost:8080/events
Content-Type: application/json

{
    "event_name":"MNG",
    "organizer_name":"KAMI",
    "event_date":"31 mei",
    "is_registered":"false"
}
